spring:
  # 專案名
  application:
    name: unhappy

  # 編碼格式
  output:
    ansi:
      enabled: always

  # 資料庫連線資訊
  datasource:
    # SQL Server設定
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=ProjectDB;trustServerCertificate=true;
    username: sa
    password: P@ssw0rd

    # 連接池設定
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  # JPA設定
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: validate

  # SMTP郵件管理
  mail:
    host: smtp.gmail.com
    port: 587
    username: jfpoie13@gmail.com
    password: tsoorupzgdgwesse
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # 媒體上傳檔案大小限制
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# user jwt
jwt:
  token:
    expire: 3600000
  # admin jwt
  secret: CyeBp5lDC8M2Gr9C+LpL0xkgoWDOhGkDjJeaV6Tf7eA=
  # front jwt service
  front:
    secret: 9affebf12fc9452aefcbcc49466f2249e831dd8f55b9e6047cef9051cedd4243518dff9b150b34511cd58fcf380692ed966fca73af1707a6e600616610467b6bf7416091850753c5b586fd88d305592e2d2d6d2333865396307ef3aa4cc7981d1788aabbf0264b1ff94726effcb293db93e2efe50429e87bdb23cf6d5b38a0ce5946f1e892a93002c72e648b0fe99ec5efc73f211233bdf712abde3d28942a92d7c06afe36c8d1f89707b7ad0c838de45e66797b5c55c6a2336b2d03053ed50637c73ac132627e33aa6709748d8f142d5c68cbd23bd5b41a9ca57845194a6e3f30d3eebaad9f01a1d245d90a9e1e444ee6d8231d3240b7d55ceeeacae2f040bd
    expiration: 86400000 # 例如 1 天的毫秒數
    
# user email
email:
  template:
    path: classpath:static/email_templates/forget_password_template.html

# Azure 儲存空間連線資訊
azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=unhappyproductmedia;AccountKey=SmVnSwDVTv4ihzV2PdozNsjg6WzTTZT4fawbW1Mx2hou1bByMZCqOGsOPUe73HyUxZ74es+qVrsc+ASt58xp/g==;EndpointSuffix=core.windows.net
    container: product-media



