spring:
  # 專案名
  application:
    name: unhappy

  # 編碼格式
  output:
    ansi:
      enabled: always

  # 資料庫連線資訊
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=ProjectDB;trustServerCertificate=true;
    username: sa
    password: P@ssw0rd

  # JPA設定
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: validate

  # SMTP郵件管理
  mail:
    host: smtp.gmail.com
    port: 587
    username: jfpoie13@gmail.com
    password: tsoorupzgdgwesse
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# user jwt
jwt:
  token:
    expire: 3600000
    
# user email
email:
  template:
    path: classpath:static/email_templates/forget_password_template.html